### ISSUE TITLE
Firmware Feature Request: Export/Import Profile

### ISSUE THREAD

**Issue by ljakob** [estkme-group/estkme-docs#5]
it would be great to be able to clone a profile from one eSTK.me-SIM to an other

some linux command line tool like for firmware update is enough since you must be knowing what you're doing

of course you can't use both profiles at the same time

**Comment by BeRealQueally** [comment]
You **cannot** and **should not** allow any data to be **cloned** from a **SecureElement**

**Comment by septs** [comment]
SGP.22 v3.x supports device change and profile recovery

but there is no eSIM chip that implements SGP.22 v3.x

---------

see <https://www.gsma.com/solutions-and-impact/technologies/esim/wp-content/uploads/2023/12/SGP.22-v3.1.pdf#page=197>

**Comment by ljakob** [comment]
thanks for your response, your mission statement "Unlike our ‘RED’ and ‘GREEN’ counterparts, we prioritize returning all freedom and privacy back to the customer while meeting GSMA requirements."... I would value the "freedom" aspect moving a profile from one device to an other higher than being secure and GSM compliant.

I'm no expert in that GSM stuff but I would guess you could implement this in a secure fashion by "pairing" two eSTK.me-chips.

... just an idea from a "prosumer"

**Comment by PeterCxy** [comment]
@ljakob The eSE firmware (SIM OS) needs to be conformant in order to be signed by GSMA. Downloading production eSIM profiles requires this signature because SM-DP+ servers perform client-side verification. Unless you can reverse-engineer an RSA4096 signature, what you have proposed is simply not possible right now.

**Comment by ljakob** [comment]
hi, thanks for the quick response - I didn't know that your firmware has to pass some kind of review process or you have legal binding to the GSMA. In that case it's clear that you are not so free... I had hoped that with a free solution I would be able to do more cloning like in the GSM-2 times when it was possible to extract the KI from most SIMs.

**Comment by PeterCxy** [comment]
@ljakob An unsigned firmware is unable to download production eSIM profiles (i.e. _any_ profile you can download from _any_ carrier) due to client-side verification. Unfortunately that is simply how eSIMs are designed to work, and there is no way around it unless, again, if you can crack an RSA4096 private key.

**Comment by CoelacanthusHex** [comment]
It's like that, technologically, your can make a Passport which works same as the Passport made by gov, but without the root certificate, any passport checker will reject your homebrew passport and the passport can't do anything useful.
